// GOVERNMENT SCHEMES & SUBSIDY DIRECTORY
// Authoritative, comprehensive database of Central & State agricultural schemes with eligibility,
// document checklists, financial assistance, and direct links to official government portals.

export const SCHEMES_DATA = [
  // ==========================================
  // CENTRAL GOVERNMENT FLAGSHIP SCHEMES
  // ==========================================
  {
    id: 'pm-kisan',
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    hindiName: 'प्रधानमंत्री किसान सम्मान निधि योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 100,
    category: 'income_credit',
    categoryLabelEn: 'Direct Income Support',
    categoryLabelHi: 'प्रत्यक्ष आय सहायता',
    benefitEn: '₹6,000 per year transferred directly via DBT into Aadhaar-linked bank accounts in 3 equal four-monthly installments of ₹2,000.',
    benefitHi: '₹6,000 प्रति वर्ष 3 समान किस्तों में (प्रत्येक ₹2,000) सीधे आधार-सीडेड बैंक खाते में डीबीटी (DBT) के माध्यम से।',
    eligibilityEn: 'All landholding farmer families having cultivable agricultural land in their name (excluding institutional landholders and high-income tax payers).',
    eligibilityHi: 'वे सभी किसान परिवार जिनके नाम पर कृषि योग्य भूमि दर्ज है (संवैधानिक पदधारक एवं आयकरदाता को छोड़कर)।',
    subsidyRate: '₹6,000 / Year DBT',
    documentsRequired: [
      { en: 'Aadhaar Card (Mandatory for e-KYC)', hi: 'आधार कार्ड (ई-केवाईसी अनिवार्य)' },
      { en: 'Land Record Khatauni / Khasra Document', hi: 'खतौनी / खसरा भू-अभिलेख' },
      { en: 'Aadhaar NPCI linked active bank passbook', hi: 'आधार एनपीसीआई से जुड़ा सक्रिय बैंक खाता' }
    ],
    applicationMethodEn: 'Register online at pmkisan.gov.in via Farmer Corner, PM-KISAN Mobile App with facial recognition, or visit nearest CSC/VLE centre.',
    applicationMethodHi: 'pmkisan.gov.in पोर्टल पर फार्मर कॉर्नर से ऑनलाइन, पीएम-किसान मोबाइल ऐप से फेशियल रिकग्निशन द्वारा, या नजदीकी सीएससी (CSC) केंद्र पर।',
    portalUrl: 'https://pmkisan.gov.in',
    tollFreeContact: '155261 / 1800-115-526 / 011-24300606',
    statusBadge: 'Active Central DBT',
    featured: true,
    tags: ['income', 'small_marginal', 'dbt', 'all_farmers']
  },
  {
    id: 'pmfby',
    name: 'PMFBY (Pradhan Mantri Fasal Bima Yojana)',
    hindiName: 'प्रधानमंत्री फसल बीमा योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 98,
    category: 'insurance_risk',
    categoryLabelEn: 'Crop Loss Insurance',
    categoryLabelHi: 'फसल नुकसान बीमा',
    benefitEn: 'Comprehensive insurance coverage against non-preventable natural risks (drought, flood, unseasonal storm, hailstorm, pest attacks). Farmer pays nominal premium: 2% for Kharif, 1.5% for Rabi, and 5% for Annual Commercial/Horticultural crops. Remaining premium subsidized by Govt.',
    benefitHi: 'प्राकृतिक आपदाओं (सूखा, बाढ़, ओलावृष्टि, कीट प्रकोप) से फसल नष्ट होने पर पूर्ण वित्तीय सुरक्षा। खरीफ के लिए मात्र 2%, रबी के लिए 1.5% और बागवानी हेतु 5% प्रीमियम। शेष राशि सरकार देती है।',
    eligibilityEn: 'All farmers (including sharecroppers and tenant farmers) growing notified crops in notified areas. Both loanee and non-loanee farmers eligible.',
    eligibilityHi: 'अधिसूचित क्षेत्रों में अधिसूचित फसल उगाने वाले सभी किसान (बटाईदार एवं काश्तकार भी शामिल)। ऋणी एवं गैर-ऋणी दोनों पात्र हैं।',
    subsidyRate: 'Up to 90% Premium Subsidized',
    documentsRequired: [
      { en: 'Sowing Certificate / Patwari Girdawari', hi: 'बोआई प्रमाण पत्र / पटवारी गिरदावरी' },
      { en: 'Land Record (7/12, RoR or Khatauni)', hi: 'भूमि रिकॉर्ड (7/12, खसरा-खतौनी)' },
      { en: 'Bank Passbook & Aadhaar Card', hi: 'बैंक पासबुक एवं आधार कार्ड' }
    ],
    applicationMethodEn: 'Enroll before cutoff date via National Crop Insurance Portal (pmfby.gov.in), authorized bank branches, or CSC centers. Intimate crop loss within 72 hours via Crop Insurance App.',
    applicationMethodHi: 'pmfby.gov.in पोर्टल, बैंक शाखा या सीएससी केंद्र से अंतिम तिथि से पूर्व आवेदन करें। फसल नुकसान की सूचना 72 घंटे के भीतर ऐप पर दें।',
    portalUrl: 'https://pmfby.gov.in',
    tollFreeContact: '14447 (National Crop Insurance Helpline)',
    statusBadge: 'Highly Recommended',
    featured: true,
    tags: ['insurance', 'disaster', 'rabi', 'kharif']
  },
  {
    id: 'kcc',
    name: 'KCC (Kisan Credit Card Scheme)',
    hindiName: 'किसान क्रेडिट कार्ड योजना',
    ministry: 'Department of Agriculture & Reserve Bank of India',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 95,
    category: 'income_credit',
    categoryLabelEn: 'Institutional Farm Credit',
    categoryLabelHi: 'रियायती कृषि ऋण',
    benefitEn: 'Short-term credit limit up to ₹3,00,000 at an effective subsidized interest rate of just 4% per annum (standard 7% minus 3% prompt repayment incentive). Collateral-free credit limit up to ₹1,60,000.',
    benefitHi: 'समय पर भुगतान करने पर मात्र 4% वार्षिक रियायती ब्याज दर पर ₹3 लाख तक का कृषि ऋण। ₹1.60 लाख तक बिना किसी बंधक (कोलेटरल-फ्री) ऋण उपलब्ध।',
    eligibilityEn: 'Individual farmers, joint cultivators, tenant farmers, oral lessees, sharecroppers, SHGs, and JLGs involved in agriculture, animal husbandry, or fisheries.',
    eligibilityHi: 'खेती, पशुपालन, या मत्स्य पालन करने वाले सभी किसान, काश्तकार, बटाईदार, स्वयं सहायता समूह (SHG) व जेएलजी।',
    subsidyRate: '4% Effective Interest Rate',
    documentsRequired: [
      { en: 'Filled Simplified KCC 1-Page Application Form', hi: 'सरलीकृत 1-पृष्ठ केसीसी आवेदन पत्र' },
      { en: 'Aadhaar Card, PAN Card or Voter ID', hi: 'पहचान प्रमाण (आधार/पैन/वोटर कार्ड)' },
      { en: 'Land Title Proof / Cultivation Certificate', hi: 'भू-स्वामित्व / काश्तकारी प्रमाण पत्र' }
    ],
    applicationMethodEn: 'Submit 1-page form at any Public Sector Bank, Regional Rural Bank (RRB), or Cooperative Bank branch with 14-day guaranteed processing.',
    applicationMethodHi: 'किसी भी राष्ट्रीयकृत बैंक, ग्रामीण बैंक अथवा सहकारी बैंक में 1-पेज फॉर्म जमा करें। 14 दिनों में त्वरित निपटान का नियम।',
    portalUrl: 'https://myscheme.gov.in/schemes/kcc',
    tollFreeContact: '1800-180-1111',
    statusBadge: 'Guaranteed 4% Rate',
    featured: true,
    tags: ['credit', 'loan', 'kcc', 'working_capital']
  },
  {
    id: 'pm-kusum',
    name: 'PM-KUSUM (Solar Agriculture Pumps Scheme)',
    hindiName: 'प्रधानमंत्री कुसुम योजना (सोलर पंप अनुदान)',
    ministry: 'Ministry of New and Renewable Energy (MNRE), GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 92,
    category: 'solar_energy',
    categoryLabelEn: 'Solar Energy & Pumps',
    categoryLabelHi: 'सौर ऊर्जा एवं सोलर पंप',
    benefitEn: 'Up to 60% combined subsidy (30% Central + 30% State) for installing standalone solar irrigation pumps (3 HP to 10 HP - Component B) and 30% bank loan support, requiring farmers to pay only 10% upfront. Also enables solar power generation on barren land (Component A).',
    benefitHi: '3 एचपी से 10 एचपी तक के स्टैंडअलोन सोलर पंप लगाने हेतु 60% तक अनुदान (30% केंद्र + 30% राज्य)। किसान को केवल 10% अंशदान देना होता है, 30% बैंक ऋण।',
    eligibilityEn: 'Individual farmers, cooperatives, panchayats, and Farmer Producer Organizations (FPOs) with cultivable land lacking grid electricity.',
    eligibilityHi: 'व्यक्तिगत किसान, ग्राम पंचायतें, सहकारी समितियां एवं एफपीओ जिनके पास सिंचाई जल स्रोत है।',
    subsidyRate: '60% Combined Subsidy',
    documentsRequired: [
      { en: 'Aadhaar Card & Land Revenue Ownership Record', hi: 'आधार कार्ड एवं भूमि मालिकाना हक प्रमाण' },
      { en: 'Certificate of Water Source (Borewell / Well / Pond)', hi: 'जल स्रोत प्रमाण (बोरवेल / कुआं / खेत तालाब)' },
      { en: 'Bank Passbook with Aadhaar linkage', hi: 'बैंक पासबुक (आधार लिंक्ड)' }
    ],
    applicationMethodEn: 'Apply via respective State Nodal Renewable Energy Agency (e.g. UPNEDA, HAREDA, KREDL) or pmkusum.mnre.gov.in. Beware of fake clone websites.',
    applicationMethodHi: 'राज्य की नोडल अक्षय ऊर्जा एजेंसी (जैसे UPNEDA, HAREDA आदि) की आधिकारिक वेबसाइट से ऑनलाइन आवेदन करें। केवल अधिकृत पोर्टल का उपयोग करें।',
    portalUrl: 'https://pmkusum.mnre.gov.in',
    tollFreeContact: '1800-180-3333',
    statusBadge: '60% Subsidy',
    featured: true,
    tags: ['solar', 'energy', 'pump', 'sustainability']
  },
  {
    id: 'pmksy',
    name: 'PMKSY - Per Drop More Crop (Micro-Irrigation)',
    hindiName: 'प्रधानमंत्री कृषि सिंचाई योजना (पर ड्रॉप मोर क्रॉप)',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 85,
    category: 'irrigation_water',
    categoryLabelEn: 'Micro-Irrigation Subsidies',
    categoryLabelHi: 'ड्रिप व स्प्रिंकलर सब्सिडी',
    benefitEn: 'Financial assistance of 55% subsidy for Small & Marginal farmers and 45% for other farmers for setting up Drip and Sprinkler irrigation systems, cutting water use by 40-50% while raising crop productivity by 25-35%.',
    benefitHi: 'ड्रिप (टपक) एवं स्प्रिंकलर (फव्वारा) सिंचाई पद्धति लगाने हेतु लघु व सीमांत किसानों को 55% तथा अन्य किसानों को 45% तक सरकारी अनुदान। 40-50% पानी की बचत।',
    eligibilityEn: 'All farmers having cultivable land with an assured water source (tube well, open well, farm pond, canal).',
    eligibilityHi: 'वे सभी किसान जिनके पास सुनिश्चित जल स्रोत (बोरवेल, कुआं, खेत तालाब, नहर) उपलब्ध है।',
    subsidyRate: '55% Subsidy (Small/Marginal)',
    documentsRequired: [
      { en: 'Land Record (Khatauni / Jamabandi)', hi: 'जमाबंदी / खतौनी भू-अभिलेख' },
      { en: 'Aadhaar Card & Bank Passbook', hi: 'आधार कार्ड एवं बैंक पासबुक' },
      { en: 'Proof of Irrigation / Water Source', hi: 'जल स्रोत / बिजली कनेक्शन का प्रमाण' }
    ],
    applicationMethodEn: 'Apply through State Department of Horticulture / Agriculture DBT portal or nearest Assistant Director of Horticulture office.',
    applicationMethodHi: 'राज्य के उद्यान / कृषि डीबीटी पोर्टल पर ऑनलाइन पंजीकरण करें या जिला उद्यान अधिकारी कार्यालय में संपर्क करें।',
    portalUrl: 'https://pmksy.gov.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: '55% Subsidy',
    featured: false,
    tags: ['irrigation', 'water', 'drip', 'sprinkler']
  },
  {
    id: 'smam',
    name: 'SMAM & Kisan Drone Scheme (Farm Mechanization)',
    hindiName: 'कृषि यंत्रीकरण उप-मिशन एवं किसान ड्रोन योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 80,
    category: 'mechanization_infra',
    categoryLabelEn: 'Machinery & Drone Subsidy',
    categoryLabelHi: 'कृषि यंत्र एवं ड्रोन अनुदान',
    benefitEn: '40% to 50% subsidy on purchase of agricultural machinery (rotavators, laser levelers, seed drills, power tillers, combine harvesters). Financial grant of up to 100% (max ₹10 Lakh) for Drone demonstration to ICAR/KVKs, 75% for FPOs, and 40-50% for individual farmers.',
    benefitHi: 'ट्रैक्टर, रोटावेटर, रीपर, सीड ड्रिल, लेजर लैंड लेवलर पर 40% से 50% अनुदान। कीटनाशक छिड़काव हेतु किसान ड्रोन पर 40% से 50% (एफपीओ को 75% तक) सब्सिडी।',
    eligibilityEn: 'Individual farmers, Custom Hiring Centres (CHCs), FPOs, cooperatives, and rural youth entrepreneurs.',
    eligibilityHi: 'व्यक्तिगत किसान, कस्टम हायरिंग सेंटर (CHC), एफपीओ, सहकारी समितियां तथा ग्रामीण युवा।',
    subsidyRate: '40% - 50% Subsidy',
    documentsRequired: [
      { en: 'Aadhaar Card & Caste Certificate (if applicable)', hi: 'आधार कार्ड एवं जाति प्रमाण पत्र (यदि लागू हो)' },
      { en: 'Land Record (Khatauni / RoR)', hi: 'भू-अभिलेख (खतौनी / 7/12)' },
      { en: 'Bank Details & Quotation of Machinery', hi: 'बैंक पासबुक एवं अधिकृत डीलर का कोटेशन' }
    ],
    applicationMethodEn: 'Register on Central Farm Machinery Portal (agrimachinery.nic.in) or your state DBT Mechanization portal.',
    applicationMethodHi: 'agrimachinery.nic.in केंद्रीय पोर्टल पर ऑनलाइन टोकन प्राप्त करें अथवा राज्य कृषि यंत्रीकरण पोर्टल पर आवेदन करें।',
    portalUrl: 'https://agrimachinery.nic.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: 'Up to 50% Off',
    featured: false,
    tags: ['machinery', 'tractor', 'drone', 'chc']
  },
  {
    id: 'soil-health-card',
    name: 'Soil Health Card Scheme',
    hindiName: 'मृदा स्वास्थ्य कार्ड योजना (स्वस्थ धरा, खेत हरा)',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 88,
    category: 'organic_sustainable',
    categoryLabelEn: 'Soil Nutrient Testing',
    categoryLabelHi: 'मृदा परीक्षण एवं पोषण',
    benefitEn: 'Free biennial testing of 12 soil parameters (N, P, K, S, Zn, Fe, Cu, Mn, Bo, pH, Electrical Conductivity, Organic Carbon) with customized fertilizer recommendations to optimize cost and restore soil fertility.',
    benefitHi: 'प्रत्येक 2 वर्ष में खेत की मिट्टी की नि:शुल्क जांच (12 प्रमुख पोषक तत्व)। संतुलित उर्वरक प्रयोग की वैज्ञानिक सलाह जिससे खेती की लागत में 15-20% की बचत होती है।',
    eligibilityEn: 'All farmers possessing agricultural land across India.',
    eligibilityHi: 'देश के सभी कृषक जिनके पास कृषि भूमि है।',
    subsidyRate: '100% Free Testing',
    documentsRequired: [
      { en: 'Aadhaar Card', hi: 'आधार कार्ड' },
      { en: 'Khasra / Survey Number of the Farm Plot', hi: 'खेत का खसरा / सर्वे नंबर' }
    ],
    applicationMethodEn: 'Submit soil samples to nearest Krishi Vigyan Kendra (KVK), block Agriculture Office, or download card directly from soilhealth.dac.gov.in.',
    applicationMethodHi: 'नजदीकी कृषि विज्ञान केंद्र (KVK) अथवा प्रखंड कृषि अधिकारी को मिट्टी का नमूना दें, या soilhealth.dac.gov.in से ऑनलाइन कार्ड डाउनलोड करें।',
    portalUrl: 'https://soilhealth.dac.gov.in',
    tollFreeContact: '011-23382012',
    statusBadge: '100% Free Service',
    featured: false,
    tags: ['soil', 'testing', 'fertilizer', 'icar']
  },
  {
    id: 'pkvy',
    name: 'PKVY (Paramparagat Krishi Vikas Yojana)',
    hindiName: 'परंपरागत कृषि विकास योजना (जैविक एवं प्राकृतिक खेती)',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 78,
    category: 'organic_sustainable',
    categoryLabelEn: 'Organic & Natural Farming',
    categoryLabelHi: 'प्राकृतिक एवं जैविक खेती',
    benefitEn: 'Financial assistance of ₹50,000 per hectare for 3 years (₹31,000 per ha provided directly to farmers through DBT for organic inputs like seeds, bio-fertilizers, vermicompost, and botanical extracts; remaining for cluster mobilization and PGS certification).',
    benefitHi: 'जैविक खेती अपनाने हेतु 3 वर्षों के लिए ₹50,000 प्रति हेक्टेयर अनुदान। ₹31,000 सीधे डीबीटी द्वारा जैविक खाद, वर्मीकम्पोस्ट, जीवामृत, बीज आदि खरीदने हेतु।',
    eligibilityEn: 'Farmers willing to form clusters of 20 or more farmers covering at least 20 hectares (50 acres) under Participatory Guarantee System (PGS) organic certification.',
    eligibilityHi: 'कम से कम 20 किसानों का समूह बनाकर 50 एकड़ क्षेत्र में पीजीएस जैविक प्रमाणीकरण के तहत प्राकृतिक खेती करने वाले किसान।',
    subsidyRate: '₹50,000 / Hectare',
    documentsRequired: [
      { en: 'Aadhaar Card & Bank Account Proof', hi: 'आधार कार्ड एवं बैंक पासबुक' },
      { en: 'Land Ownership Document (Khatauni)', hi: 'भू-अभिलेख खतौनी' },
      { en: 'Cluster Group Member Registration Form', hi: 'क्लस्टर समूह सदस्यता सहमति पत्र' }
    ],
    applicationMethodEn: 'Contact Regional Council or Block Agriculture Technology Management Agency (ATMA) office to join an organic cluster.',
    applicationMethodHi: 'प्रखंड आत्मा (ATMA) कार्यालय अथवा जिला कृषि अधिकारी से संपर्क कर जैविक क्लस्टर में सम्मिलित हों।',
    portalUrl: 'https://pgsindia-ncof.gov.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: '₹50,000/ha Support',
    featured: false,
    tags: ['organic', 'natural_farming', 'bio_fertilizer', 'pgs']
  },
  {
    id: 'aif',
    name: 'Agriculture Infrastructure Fund (AIF)',
    hindiName: 'कृषि अवसंरचना कोष (AIF - ₹1 लाख करोड़)',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 75,
    category: 'mechanization_infra',
    categoryLabelEn: 'Post-Harvest Infrastructure',
    categoryLabelHi: 'कटाई उपरांत अवसंरचना',
    benefitEn: 'Pan-India financing facility of ₹1 Lakh Crore providing 3% interest subvention per annum for loans up to ₹2 Crore for a period of up to 7 years, along with Credit Guarantee coverage under CGTMSE for building post-harvest cold storage, pack-houses, silos, sorting/grading units, and primary processing centres.',
    benefitHi: 'कोल्ड स्टोरेज, वेयरहाउस, पैक हाउस, सॉर्टिंग व ग्रेडिंग प्लांट, प्राथमिक प्रसंस्करण केंद्र स्थापित करने हेतु ₹2 करोड़ तक के ऋण पर 7 वर्षों के लिए 3% वार्षिक ब्याज छूट और मुफ्त क्रेडिट गारंटी।',
    eligibilityEn: 'Individual Farmers, FPOs, PACS, Agri-entrepreneurs, Startups, and Central/State agencies.',
    eligibilityHi: 'व्यक्तिगत किसान, एफपीओ, पैक्स (PACS), कृषि उद्यमी, स्वयं सहायता समूह एवं स्टार्टअप्स।',
    subsidyRate: '3% Interest Subvention',
    documentsRequired: [
      { en: 'Detailed Project Report (DPR)', hi: 'विस्तृत परियोजना रिपोर्ट (DPR)' },
      { en: 'Land Ownership or Registered Lease Deed', hi: 'भूमि स्वामित्व अथवा पंजीकृत लीज डीड' },
      { en: 'KYC Documents & Balance Sheets / ITR', hi: 'केवाईसी दस्तावेज, बैंक स्टेटमेंट व पैन कार्ड' }
    ],
    applicationMethodEn: 'Submit project proposal directly online at agriinfra.dac.gov.in for fast-track ministry appraisal and bank sanction.',
    applicationMethodHi: 'agriinfra.dac.gov.in पोर्टल पर ऑनलाइन प्रोजेक्ट प्रस्ताव सबमिट करें। मंत्रालय की त्वरित स्वीकृति उपरांत बैंक से ऋण।',
    portalUrl: 'https://agriinfra.dac.gov.in',
    tollFreeContact: '011-23382444',
    statusBadge: '₹2 Cr Subsidized Loan',
    featured: false,
    tags: ['infrastructure', 'cold_storage', 'pack_house', 'processing']
  },
  {
    id: 'enam',
    name: 'e-NAM (National Agriculture Market)',
    hindiName: 'ई-नाम (राष्ट्रीय कृषि बाजार - डिजिटल मंडी)',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 84,
    category: 'fpo_market',
    categoryLabelEn: 'Direct Pan-India Market',
    categoryLabelHi: 'अखिल भारतीय डिजिटल मंडी',
    benefitEn: 'Pan-India electronic trading portal networking over 1,361 APMC mandis across 23 states. Enables farmers to showcase produce quality via electronic assaying, receive competitive bids from buyers across India, and get instant direct bank payments without middlemen cuts.',
    benefitHi: 'देश भर की 1,361 से अधिक मंडियों का एकीकृत ऑनलाइन नेटवर्क। फसल की गुणवत्ता जांच, ऑनलाइन बोली (नीलामी), पारदर्शी मूल्य खोज तथा सीधे बैंक खाते में तत्काल भुगतान। बिचौलियों से मुक्ति।',
    eligibilityEn: 'Any farmer, trader, commission agent, or FPO selling agricultural produce in registered APMCs.',
    eligibilityHi: 'कोई भी किसान, व्यापारी अथवा किसान उत्पादक संगठन (FPO) जो अपनी उपज बेचना चाहता है।',
    subsidyRate: 'Zero Commission Pan-India',
    documentsRequired: [
      { en: 'Aadhaar Card', hi: 'आधार कार्ड' },
      { en: 'Bank Account Passbook (for online payment receipt)', hi: 'बैंक पासबुक (ऑनलाइन भुगतान प्राप्त करने हेतु)' },
      { en: 'Mobile Number for OTP and SMS bid alerts', hi: 'ओटीपी व एसएमएस सूचना हेतु मोबाइल नंबर' }
    ],
    applicationMethodEn: 'Register free at enam.gov.in or e-NAM Mobile App, or carry produce to any e-NAM integrated APMC gate for free weighment & assaying.',
    applicationMethodHi: 'enam.gov.in या ई-नाम ऐप पर नि:शुल्क पंजीकरण करें, अथवा ई-नाम मंडी के प्रवेश द्वार पर उपज लाकर निःशुल्क लॉट बनवाएं।',
    portalUrl: 'https://enam.gov.in',
    tollFreeContact: '1800-270-0224',
    statusBadge: '1,361+ Mandis Live',
    featured: true,
    tags: ['mandi', 'market', 'enam', 'fair_price']
  },
  {
    id: 'fpo-scheme',
    name: 'Formation & Promotion of 10,000 FPOs',
    hindiName: '10,000 किसान उत्पादक संगठन (FPO) योजना',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 72,
    category: 'fpo_market',
    categoryLabelEn: 'Collective Farmer Enterprise',
    categoryLabelHi: 'किसान समूह एवं कंपनी',
    benefitEn: 'Matching equity grant up to ₹15 Lakh per FPO (₹2,000 per farmer member) and credit guarantee cover up to ₹2 Crore per FPO to enhance borrowing power from financial institutions. Also provides management cost support up to ₹18 Lakh for 3 years.',
    benefitHi: 'प्रति एफपीओ ₹15 लाख तक की समतुल्य इक्विटी सहायता (₹2,000 प्रति सदस्य) तथा ₹2 करोड़ तक बैंक ऋण पर मुफ्त क्रेडिट गारंटी। 3 वर्ष हेतु प्रबंधन सहायता भी।',
    eligibilityEn: 'Groups of minimum 300 farmers in plain areas (100 farmers in North Eastern & Hilly areas) registering as a Producer Company or Cooperative Society.',
    eligibilityHi: 'मैदानी क्षेत्रों में कम से कम 300 किसानों (पहाड़ी क्षेत्रों में 100) का पंजीकृत उत्पादक संगठन या सहकारी समिति।',
    subsidyRate: '₹15 Lakh Equity Grant',
    documentsRequired: [
      { en: 'FPO Certificate of Incorporation / Bye-laws', hi: 'कंपनी / सोसाइटी पंजीकरण प्रमाण पत्र' },
      { en: 'Member Farmer Shareholder List with Aadhaar', hi: 'सदस्य किसानों की आधार प्रमाणित शेयर सूची' },
      { en: 'Audited Financials / Bank Statement & Business Plan', hi: 'ऑडिट वित्तीय विवरण एवं व्यापार योजना' }
    ],
    applicationMethodEn: 'Contact designated Implementing Agencies: SFAC, NABARD, NCDC, or visit enafpo.gov.in.',
    applicationMethodHi: 'नाबार्ड (NABARD), एसएफएसी (SFAC), या एनसीडीसी (NCDC) के जिला कार्यालय में संपर्क करें।',
    portalUrl: 'https://sfacindia.com',
    tollFreeContact: '1800-180-1551',
    statusBadge: '₹15 Lakh Grant',
    featured: false,
    tags: ['fpo', 'collective', 'equity', 'cooperative']
  },
  {
    id: 'pm-kmy',
    name: 'PM-KMY (Pradhan Mantri Kisan Maan Dhan Yojana)',
    hindiName: 'प्रधानमंत्री किसान मानधन योजना (मासिक पेंशन)',
    ministry: 'Ministry of Agriculture & Farmers Welfare, GoI',
    isCentral: true,
    state: 'All India',
    stateHi: 'अखिल भारतीय',
    priority: 70,
    category: 'income_credit',
    categoryLabelEn: 'Old Age Farmer Pension',
    categoryLabelHi: 'बुढ़ापा पेंशन योजना',
    benefitEn: 'Assured monthly pension of ₹3,000 after attaining 60 years of age. Farmers contribute nominal monthly amount of ₹55 to ₹200 (depending on entry age between 18-40 years), with equal 50% matching contribution by Central Govt.',
    benefitHi: '60 वर्ष की आयु पूर्ण होने पर ₹3,000 प्रति माह निश्चित सामाजिक सुरक्षा पेंशन। 18 से 40 वर्ष की आयु में ₹55 से ₹200 प्रतिमाह अंशदान, समान 50% अंशदान केंद्र सरकार द्वारा।',
    eligibilityEn: 'Small and marginal farmers aged between 18 and 40 years possessing cultivable agricultural land up to 2 hectares (5 acres).',
    eligibilityHi: '18 से 40 वर्ष के लघु एवं सीमांत किसान जिनके पास 2 हेक्टेयर (5 एकड़) तक कृषि भूमि है।',
    subsidyRate: '₹3,000 / Month Pension',
    documentsRequired: [
      { en: 'Aadhaar Card', hi: 'आधार कार्ड' },
      { en: 'Savings Bank Account Passbook / IFSC code', hi: 'बचत बैंक खाता पासबुक' },
      { en: 'Copy of Land Records (Khatauni / Khasra)', hi: 'भू-अभिलेख खतौनी की प्रति' }
    ],
    applicationMethodEn: 'Enroll at nearest Common Services Centre (CSC) or self-enroll at maandhan.in or pmkisan portal using PM-KISAN auto-debit.',
    applicationMethodHi: 'नजदीकी सीएससी केंद्र पर जाकर पंजीकरण कराएं अथवा maandhan.in पर पीएम-किसान खाते से ऑटो-डेबिट का विकल्प चुनें।',
    portalUrl: 'https://maandhan.in',
    tollFreeContact: '1800-267-6888',
    statusBadge: '₹3,000/mo Pension',
    featured: false,
    tags: ['pension', 'senior', 'small_marginal', 'social_security']
  },

  // ==========================================
  // STATE GOVERNMENT SCHEMES (STATE PRIORITIZED)
  // ==========================================

  // --- HARYANA (हरियाणा) ---
  {
    id: 'meri-fasal-mera-byora',
    name: 'Meri Fasal Mera Byora (मेरी फसल मेरा ब्यौरा)',
    hindiName: 'मेरी फसल मेरा ब्यौरा पोर्टल पंजीकरण',
    ministry: 'Department of Agriculture & Farmers Welfare, Govt of Haryana',
    isCentral: false,
    state: 'Haryana',
    stateHi: 'हरियाणा',
    priority: 96,
    category: 'fpo_market',
    categoryLabelEn: 'State Procurement & Welfare',
    categoryLabelHi: 'राज्य उपार्जन एवं कल्याण',
    benefitEn: 'Mandatory single-window portal registration for 100% MSP procurement of wheat, paddy, mustard, and bajra. Offers financial incentive of ₹100/acre upon early registration, automatic disaster compensation directly into DBT account, and eligibility for all Haryana farm subsidies.',
    benefitHi: 'गेहूं, धान, सरसों और बाजरा की 100% एमएसपी खरीद हेतु अनिवार्य एकल-खिड़की पंजीकरण। समय पर पंजीकरण पर ₹100 प्रति एकड़ प्रोत्साहन, सीधी डीबीटी आपदा राहत, एवं समस्त राज्य सब्सिडी की पात्रता।',
    eligibilityEn: 'All landholding, tenant, and lease farmers cultivating land within the state of Haryana.',
    eligibilityHi: 'हरियाणा राज्य में कृषि भूमि जोतने वाले सभी भू-स्वामी, काश्तकार एवं पट्टेदार किसान।',
    subsidyRate: '100% MSP Procurement Guarantee',
    documentsRequired: [
      { en: 'Parivar Pehchan Patra (PPP / Family ID)', hi: 'परिवार पहचान पत्र (PPP / फैमिली आईडी)' },
      { en: 'Murabba / Kila Land Revenue Number (Jamabandi)', hi: 'मुरब्बा / किला नंबर (जमाबंदी रिकॉर्ड)' },
      { en: 'Aadhaar Card and Active Bank Passbook', hi: 'आधार कार्ड एवं सक्रिय बैंक खाता पासबुक' }
    ],
    applicationMethodEn: 'Register crop details at fasal.haryana.gov.in before seasonal cutoff or via nearest CSC Atal Seva Kendra.',
    applicationMethodHi: 'fasal.haryana.gov.in पोर्टल पर फसल विवरण दर्ज करें अथवा नजदीकी अटल सेवा केंद्र / सीएससी पर जाएं।',
    portalUrl: 'https://fasal.haryana.gov.in',
    tollFreeContact: '1800-180-2117 / 1800-180-2060',
    statusBadge: 'Haryana Mandatory Portal',
    featured: true,
    tags: ['haryana', 'msp', 'procurement', 'dbt']
  },
  {
    id: 'bhavantar-bharpayee-haryana',
    name: 'Bhavantar Bharpayee Yojana (भावांतर भरपाई योजना)',
    hindiName: 'भावांतर भरपाई योजना (सब्जी व बाजरा मूल्य सुरक्षा)',
    ministry: 'Haryana State Agricultural Marketing Board (HSAMB)',
    isCentral: false,
    state: 'Haryana',
    stateHi: 'हरियाणा',
    priority: 94,
    category: 'income_credit',
    categoryLabelEn: 'Price Deficit Protection',
    categoryLabelHi: 'मूल्य घाटा भरपाई',
    benefitEn: 'Guaranteed minimum floor price for 21 horticulture crops (potato, onion, tomato, cauliflower, peas, carrots, guava, kinnu) and Bajra/Millet. If market price falls below protected floor price, Govt transfers the price deficit difference directly to the farmer bank account via DBT.',
    benefitHi: '21 बागवानी फसलों (आलू, प्याज, टमाटर, फूलगोभी, मटर, अमरूद आदि) एवं बाजरा हेतु संरक्षित आधार मूल्य की गारंटी। मंडी भाव कम रहने पर अंतर राशि सीधे डीबीटी द्वारा खाते में।',
    eligibilityEn: 'Farmers registered on Meri Fasal Mera Byora selling produce in designated Haryana APMC mandis.',
    eligibilityHi: 'मेरी फसल मेरा ब्यौरा पोर्टल पर पंजीकृत किसान जो हरियाणा की अधिसूचित मंडियों में उपज बेचते हैं।',
    subsidyRate: '100% Price Gap Compensation',
    documentsRequired: [
      { en: 'Meri Fasal Mera Byora Registration Slip', hi: 'मेरी फसल मेरा ब्यौरा पंजीकरण पर्ची' },
      { en: 'APMC Mandi J-Form (Sale Voucher)', hi: 'अनाज मंडी जे-फॉर्म (बिक्री पर्ची)' },
      { en: 'Aadhaar Linked Bank Account Details', hi: 'आधार लिंक्ड बैंक खाता विवरण' }
    ],
    applicationMethodEn: 'Register on fasal.haryana.gov.in during sowing and upload J-Form from mandi sale.',
    applicationMethodHi: 'फसल बोआई के समय fasal.haryana.gov.in पर पंजीकरण करें और मंडी में फसल बेचने के बाद जे-फॉर्म अपलोड करें।',
    portalUrl: 'https://agriharyana.gov.in',
    tollFreeContact: '1800-180-2117',
    statusBadge: 'Price Floor Guarantee',
    featured: true,
    tags: ['haryana', 'horticulture', 'bhavantar', 'vegetables']
  },
  {
    id: 'mera-pani-meri-virasat',
    name: 'Mera Pani Meri Virasat (मेरा पानी मेरी विरासत)',
    hindiName: 'मेरा पानी मेरी विरासत योजना (₹7,000/एकड़ नकद अनुदान)',
    ministry: 'Department of Agriculture & Farmers Welfare, Govt of Haryana',
    isCentral: false,
    state: 'Haryana',
    stateHi: 'हरियाणा',
    priority: 91,
    category: 'irrigation_water',
    categoryLabelEn: 'Crop Diversification Incentive',
    categoryLabelHi: 'फसल विविधीकरण अनुदान',
    benefitEn: 'Financial cash incentive of ₹7,000 per acre provided directly to farmers who switch from water-guzzling paddy (dhan) cultivation to alternative low-water crops like maize, cotton, pulses, oilseeds, or keep fields fallow for underground water conservation.',
    benefitHi: 'धान (चावल) की जगह मक्का, कपास, दलहन, तिलहन की खेती करने अथवा खेत खाली रखने पर ₹7,000 प्रति एकड़ नकद वित्तीय प्रोत्साहन सीधे बैंक खाते में।',
    eligibilityEn: 'Farmers in Haryana replacing paddy cultivation in dark zone blocks with alternate crops.',
    eligibilityHi: 'हरियाणा के वे किसान जो धान की जगह वैकल्पिक फसलें लगाते हैं।',
    subsidyRate: '₹7,000 / Acre Cash DBT',
    documentsRequired: [
      { en: 'Fasal Haryana Registration Verification', hi: 'फसल हरियाणा पोर्टल सत्यापन' },
      { en: 'Aadhaar Card and Land Record Jamabandi', hi: 'आधार कार्ड एवं जमाबंदी नकल' },
      { en: 'Bank Passbook linked with Aadhaar', hi: 'आधार लिंक्ड बैंक पासबुक' }
    ],
    applicationMethodEn: 'Apply on fasal.haryana.gov.in under Mera Pani Meri Virasat tab before 15th July every year.',
    applicationMethodHi: 'fasal.haryana.gov.in पर मेरा पानी मेरी विरासत टैब पर प्रतिवर्ष 15 जुलाई से पहले आवेदन करें।',
    portalUrl: 'https://fasal.haryana.gov.in',
    tollFreeContact: '1800-180-2117',
    statusBadge: '₹7,000/Acre Grant',
    featured: false,
    tags: ['haryana', 'water', 'conservation', 'diversification']
  },
  {
    id: 'haryana-solar-pump',
    name: 'Haryana Solar Water Pumping Scheme (सरल पोर्टल सोलर पंप)',
    hindiName: 'हरियाणा सोलर वाटर पंप योजना (75% सब्सिडी)',
    ministry: 'New & Renewable Energy Department (HAREDA), Haryana',
    isCentral: false,
    state: 'Haryana',
    stateHi: 'हरियाणा',
    priority: 90,
    category: 'solar_energy',
    categoryLabelEn: 'High-Subsidy Solar Pumps',
    categoryLabelHi: 'सोलर पंप 75% अनुदान',
    benefitEn: '75% comprehensive subsidy for standalone 3 HP to 10 HP solar water pumping systems under PM-KUSUM Component B. Farmers pay only 25% cost to replace polluting diesel engines with zero-electricity-bill solar power.',
    benefitHi: '3 एचपी से 10 एचपी सोलर वाटर पंपिंग सिस्टम पर 75% सरकारी अनुदान। किसान को केवल 25% लागत वहन करनी होती है। शून्य बिजली बिल पर खेतों में सिंचाई।',
    eligibilityEn: 'Farmers having cultivable land with borewell/open pond, registered on Parivar Pehchan Patra (PPP). Farmers with existing grid electricity connections are not eligible for new standalone pumps.',
    eligibilityHi: 'परिवार पहचान पत्र (PPP) धारक किसान जिनके पास सिंचाई हेतु बोरवेल या जल स्रोत उपलब्ध है।',
    subsidyRate: '75% State & Central Subsidy',
    documentsRequired: [
      { en: 'Parivar Pehchan Patra (Family ID)', hi: 'परिवार पहचान पत्र (फैमिली आईडी)' },
      { en: 'Land Jamabandi & Water Source Proof', hi: 'भूमि की जमाबंदी एवं जल स्रोत प्रमाण' },
      { en: 'Bank Account Passbook & Aadhaar', hi: 'बैंक पासबुक एवं आधार कार्ड' }
    ],
    applicationMethodEn: 'Apply online on Antyodaya Saral Portal (saralharyana.gov.in) when application windows open.',
    applicationMethodHi: 'सरल हरियाणा पोर्टल (saralharyana.gov.in) पर ऑनलाइन आवेदन करें।',
    portalUrl: 'https://saralharyana.gov.in',
    tollFreeContact: '0172-3968400 / 1800-180-3333',
    statusBadge: '75% Subsidy Rate',
    featured: false,
    tags: ['haryana', 'solar', 'pump', 'energy']
  },

  // --- PUNJAB (पंजाब) ---
  {
    id: 'punjab-crm-subsidy',
    name: 'Punjab Crop Residue Management Subsidy (फसल अवशेष प्रबंधन मशीनरी)',
    hindiName: 'पंजाब पराली प्रबंधन कृषि यंत्र अनुदान (50-80% सब्सिडी)',
    ministry: 'Department of Agriculture & Farmers Welfare, Govt of Punjab',
    isCentral: false,
    state: 'Punjab',
    stateHi: 'पंजाब',
    priority: 95,
    category: 'mechanization_infra',
    categoryLabelEn: 'Stubble Machinery Grant',
    categoryLabelHi: 'पराली प्रबंधन यंत्र अनुदान',
    benefitEn: '50% individual subsidy and 80% community subsidy for Custom Hiring Centres (CHCs), Co-operative societies, and Panchayats on specialized stubble-management machinery: Super SMS, Happy Seeder, Smart Seeder, Paddy Straw Chopper, Mulcher, and Zero Till Drills to eliminate stubble burning.',
    benefitHi: 'पराली जलाने की समस्या रोकने हेतु हैप्पी सीडर, सुपर एसएमएस, स्मार्ट सीडर, पैडी स्ट्रॉ चॉपर एवं मल्चर पर व्यक्तिगत किसानों को 50% तथा किसान समूहों/सहकारी समितियों को 80% तक अनुदान।',
    eligibilityEn: 'All farmers, farmer groups, primary agricultural credit societies (PACS), and Panchayats in Punjab.',
    eligibilityHi: 'पंजाब के व्यक्तिगत किसान, स्वयं सहायता समूह, पैक्स एवं ग्राम पंचायतें।',
    subsidyRate: '50% - 80% Machinery Subsidy',
    documentsRequired: [
      { en: 'Aadhaar Card and Land Record (Fard / Jamabandi)', hi: 'आधार कार्ड एवं फर्द/जमाबंदी भू-अभिलेख' },
      { en: 'Tractor Registration Certificate (RC)', hi: 'ट्रैक्टर आरसी (पंजीकरण प्रमाण पत्र)' },
      { en: 'Bank Passbook and Quotation from Approved Dealer', hi: 'बैंक पासबुक एवं अधिकृत डीलर कोटेशन' }
    ],
    applicationMethodEn: 'Apply online on Punjab Agriculture Mechanization Portal (agripb.gov.in). Selection made via automated lottery.',
    applicationMethodHi: 'agripb.gov.in पोर्टल पर ऑनलाइन टोकन आवेदन करें। चयन ऑनलाइन लॉटरी से होता है।',
    portalUrl: 'https://agripb.gov.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: '50% to 80% Subsidy',
    featured: true,
    tags: ['punjab', 'stubble', 'machinery', 'environment']
  },
  {
    id: 'paani-bachao-paise-kamao',
    name: 'Paani Bachao, Paise Kamao (पानी बचाओ, पैसे कमाओ)',
    hindiName: 'पानी बचाओ, पैसे कमाओ योजना (₹4/यूनिट डायरेक्ट कैश)',
    ministry: 'Punjab State Power Corporation Limited (PSPCL) & Govt of Punjab',
    isCentral: false,
    state: 'Punjab',
    stateHi: 'पंजाब',
    priority: 92,
    category: 'irrigation_water',
    categoryLabelEn: 'Groundwater Cash Transfer',
    categoryLabelHi: 'भूजल बचत नकद पुरस्कार',
    benefitEn: 'Direct financial cash reward of ₹4 per kilowatt-hour (kWh) deposited directly into farmers bank accounts for voluntarily saving electricity and underground irrigation water by installing electricity meters on agricultural tubewells without affecting free power supply entitlement.',
    benefitHi: 'कृषि नलकूपों पर मीटर लगाकर भूजल एवं बिजली की बचत करने पर ₹4 प्रति यूनिट (kWh) का सीधा नकद पुरस्कार बैंक खाते में। मुफ्त बिजली का अधिकार यथावत बना रहता है।',
    eligibilityEn: 'Farmers having agricultural tubewell electricity connections under selected pilot feeders in Punjab.',
    eligibilityHi: 'पंजाब के अधिसूचित फीडरों पर कृषि बिजली कनेक्शन वाले नलकूप धारक किसान।',
    subsidyRate: '₹4 / kWh Direct Cash Transfer',
    documentsRequired: [
      { en: 'Tubewell Electricity Consumer Account Number', hi: 'नलकूप बिजली उपभोक्ता खाता संख्या' },
      { en: 'Aadhaar Card and Active Bank Passbook', hi: 'आधार कार्ड एवं बैंक पासबुक' },
      { en: 'Land Record Proof', hi: 'भू-स्वामित्व प्रमाण पत्र' }
    ],
    applicationMethodEn: 'Enroll at local PSPCL sub-division office or via PSPCL portal to consent for voluntary meter installation.',
    applicationMethodHi: 'स्थानीय पीएसपीसीएल उप-मंडल कार्यालय में संपर्क कर मीटर लगाने की सहमति दें।',
    portalUrl: 'https://pspcl.in',
    tollFreeContact: '1912 (PSPCL Electricity Helpline)',
    statusBadge: '₹4/Unit Cash Reward',
    featured: false,
    tags: ['punjab', 'water', 'electricity', 'cash']
  },
  {
    id: 'punjab-karz-rahat',
    name: 'Punjab Kisan Karz Rahat Scheme (पंजाब किसान कर्ज राहत योजना)',
    hindiName: 'पंजाब किसान ऋण राहत योजना (₹2 लाख तक कर्ज माफी)',
    ministry: 'Department of Cooperation, Govt of Punjab',
    isCentral: false,
    state: 'Punjab',
    stateHi: 'पंजाब',
    priority: 88,
    category: 'income_credit',
    categoryLabelEn: 'Cooperative Debt Relief',
    categoryLabelHi: 'सहकारी ऋण राहत',
    benefitEn: 'Institutional farm debt waiver of up to ₹2,00,000 for small (2.5 to 5 acres) and marginal (< 2.5 acres) farmers having crop loans with cooperative and commercial banks.',
    benefitHi: 'सहकारी एवं वाणिज्यिक बैंकों से लिए गए ₹2,00,000 तक के कृषि ऋणों की पूर्ण कर्ज माफी। 5 एकड़ तक की जोत वाले लघु एवं सीमांत किसानों हेतु।',
    eligibilityEn: 'Small and marginal farmers holding agricultural land up to 5 acres in Punjab with default loans.',
    eligibilityHi: 'पंजाब के 5 एकड़ तक की भूमि वाले लघु व सीमांत किसान।',
    subsidyRate: 'Up to ₹2 Lakh Loan Waiver',
    documentsRequired: [
      { en: 'Cooperative Bank Loan Passbook', hi: 'सहकारी बैंक ऋण पासबुक' },
      { en: 'Aadhaar Card and Land Fard Document', hi: 'आधार कार्ड एवं जमीन की फर्द' }
    ],
    applicationMethodEn: 'Verify list at local Primary Agricultural Cooperative Society (PACS) or Deputy Commissioner office.',
    applicationMethodHi: 'स्थानीय प्राथमिक कृषि सहकारी समिति (PACS) में लाभार्थी सूची में नाम सत्यापित करें।',
    portalUrl: 'https://agripb.gov.in',
    tollFreeContact: '0172-2970605',
    statusBadge: '₹2 Lakh Waiver',
    featured: false,
    tags: ['punjab', 'loan', 'debt', 'waiver']
  },

  // --- UTTAR PRADESH (उत्तर प्रदेश) ---
  {
    id: 'up-khet-talab',
    name: 'UP Khet Talab Yojana (उत्तर प्रदेश खेत तालाब योजना)',
    hindiName: 'खेत तालाब योजना (50% सीधा सरकारी अनुदान)',
    ministry: 'Department of Agriculture, Govt of Uttar Pradesh',
    isCentral: false,
    state: 'Uttar Pradesh',
    stateHi: 'उत्तर प्रदेश',
    priority: 95,
    category: 'irrigation_water',
    categoryLabelEn: 'Farm Pond Subsidy',
    categoryLabelHi: 'खेत तालाब 50% अनुदान',
    benefitEn: '50% direct subsidy up to ₹52,500 for small ponds (22m x 20m x 3m) and ₹1,14,200 for medium farm ponds directly into the farmer DBT account for rainwater harvesting, ground recharging, and protective irrigation during drought spells in Bundelkhand and Purvanchal.',
    benefitHi: 'वर्षा जल संचयन एवं सूखे से सुरक्षा हेतु खेत में तालाब खुदवाने पर 50% सरकारी अनुदान (छोटे तालाब पर ₹52,500 एवं मध्यम पर ₹1,14,200) सीधे डीबीटी बैंक खाते में।',
    eligibilityEn: 'All farmers of Uttar Pradesh possessing land in Bundelkhand and drought-prone regions with cultivable land.',
    eligibilityHi: 'उत्तर प्रदेश के सभी किसान जिनके पास तालाब निर्माण हेतु पर्याप्त कृषि भूमि उपलब्ध है।',
    subsidyRate: '50% Subsidy (₹52,500 to ₹1,14,200)',
    documentsRequired: [
      { en: 'Khatauni / Khasra Land Records', hi: 'खतौनी / खसरा भू-अभिलेख' },
      { en: 'Aadhaar Card & Bank Passbook', hi: 'आधार कार्ड एवं बैंक पासबुक' },
      { en: 'Self-declaration token slip', hi: 'टोकन पंजीकरण रसीद' }
    ],
    applicationMethodEn: 'Book token online on Pardarshi Kisan Seva Portal (upagriculture.com) under Farm Pond Scheme.',
    applicationMethodHi: 'पारदर्शी किसान सेवा पोर्टल (upagriculture.com) पर ऑनलाइन टोकन बुक करें और अग्रिम राशि जमा कराएं।',
    portalUrl: 'https://upagriculture.com',
    tollFreeContact: '1800-180-1551 / 0522-2204223',
    statusBadge: '50% Farm Pond Grant',
    featured: true,
    tags: ['uttar pradesh', 'water', 'pond', 'irrigation']
  },
  {
    id: 'up-krishi-yantra',
    name: 'UP Krishi Yantra Anudan E-Lottery (कृषि यंत्र अनुदान टोकन प्रणाली)',
    hindiName: 'पारदर्शी किसान सेवा ई-लॉटरी कृषि यंत्र अनुदान',
    ministry: 'Department of Agriculture, Uttar Pradesh',
    isCentral: false,
    state: 'Uttar Pradesh',
    stateHi: 'उत्तर प्रदेश',
    priority: 92,
    category: 'mechanization_infra',
    categoryLabelEn: 'Transparent Machinery Subsidies',
    categoryLabelHi: 'कृषि यंत्र 50% अनुदान',
    benefitEn: '40% to 50% subsidy on agricultural implements (rotavator, thresher, seed drill, laser leveler, tractor) allocated transparently through online e-Lottery tokens on upagriculture.com with direct DBT credit.',
    benefitHi: 'पारदर्शी किसान सेवा पोर्टल (upagriculture.com) पर ई-लॉटरी टोकन द्वारा रोटावेटर, थ्रेशर, सीड ड्रिल, लेजर लेवलर आदि कृषि यंत्रों पर 40% से 50% तक सीधा अनुदान।',
    eligibilityEn: 'Farmers registered on upagriculture.com with valid farmer registration number and Aadhaar.',
    eligibilityHi: 'upagriculture.com पर पंजीकृत किसान जिनके पास किसान पंजीकरण संख्या उपलब्ध है।',
    subsidyRate: '40% - 50% DBT Grant',
    documentsRequired: [
      { en: 'UP Farmer Registration ID (Kisan Panjikaran)', hi: 'किसान पंजीकरण संख्या' },
      { en: 'Aadhaar Card and Land Khatauni', hi: 'आधार कार्ड एवं भू-अभिलेख खतौनी' },
      { en: 'Security token deposit demand draft / online receipt', hi: 'जमानत धनराशि रसीद' }
    ],
    applicationMethodEn: 'Generate token online at upagriculture.com, submit security deposit, and participate in district e-Lottery.',
    applicationMethodHi: 'upagriculture.com पर ऑनलाइन टोकन जनरेट करें और जिला स्तरीय ई-लॉटरी में भाग लें।',
    portalUrl: 'https://upagriculture.com',
    tollFreeContact: '0522-2204223',
    statusBadge: 'Up to 50% Off',
    featured: false,
    tags: ['uttar pradesh', 'machinery', 'tractor', 'token']
  },
  {
    id: 'up-solar-pump',
    name: 'UP Solar Tubewell / KUSUM-C Yojana (सोलर नलकूप योजना)',
    hindiName: 'यूपी सोलर नलकूप एवं कुसुम योजना (60-70% अनुदान)',
    ministry: 'UP New & Renewable Energy Development Agency (UPNEDA)',
    isCentral: false,
    state: 'Uttar Pradesh',
    stateHi: 'उत्तर प्रदेश',
    priority: 89,
    category: 'solar_energy',
    categoryLabelEn: 'Solar Tubewell Subsidy',
    categoryLabelHi: 'सोलर नलकूप 60-70% अनुदान',
    benefitEn: '60% to 70% joint subsidy (Central + UP State) for solarizing existing electric and diesel agricultural tube wells under PM-KUSUM Component C-1 with zero electricity tariff and surplus power feed-in.',
    benefitHi: 'निजी नलकूपों के सोलराइजेशन हेतु 60% से 70% तक संयुक्त सरकारी अनुदान। दिन में मुफ्त सिंचाई और बिजली बिल से पूर्ण मुक्ति।',
    eligibilityEn: 'Farmers having functional electric tubewell connections or boring in Uttar Pradesh.',
    eligibilityHi: 'उत्तर प्रदेश के किसान जिनके पास निजी नलकूप या बोरिंग उपलब्ध है।',
    subsidyRate: '60% - 70% Joint Subsidy',
    documentsRequired: [
      { en: 'Electricity connection bill or boring certificate', hi: 'विद्युत कनेक्शन बिल अथवा बोरिंग प्रमाण पत्र' },
      { en: 'Khatauni and Aadhaar Card', hi: 'खतौनी एवं आधार कार्ड' },
      { en: 'Bank Account Passbook', hi: 'बैंक पासबुक' }
    ],
    applicationMethodEn: 'Apply on upneda.org.in or upagriculture.com when the solar pump token booking window is notified.',
    applicationMethodHi: 'upneda.org.in या upagriculture.com पर सोलर पंप टोकन बुकिंग शुरू होने पर आवेदन करें।',
    portalUrl: 'https://upneda.org.in',
    tollFreeContact: '0522-2720652',
    statusBadge: '60-70% Solar Grant',
    featured: false,
    tags: ['uttar pradesh', 'solar', 'tubewell', 'pump']
  },

  // --- MADHYA PRADESH (मध्य प्रदेश) ---
  {
    id: 'mp-kisan-kalyan',
    name: 'Mukhyamantri Kisan Kalyan Yojana (मुख्यमंत्री किसान कल्याण योजना)',
    hindiName: 'मुख्यमंत्री किसान कल्याण योजना (₹6,000 अतिरिक्त राज्य DBT)',
    ministry: 'Revenue & Agriculture Department, Govt of Madhya Pradesh',
    isCentral: false,
    state: 'Madhya Pradesh',
    stateHi: 'मध्य प्रदेश',
    priority: 97,
    category: 'income_credit',
    categoryLabelEn: 'State Supplementary DBT',
    categoryLabelHi: 'राज्य अतिरिक्त डीबीटी (कुल ₹12,000)',
    benefitEn: 'State DBT of ₹6,000 per year transferred in 3 equal installments of ₹2,000 directly into the bank accounts of all PM-KISAN eligible farmers of MP. Combined with PM-KISAN (₹6,000 Central + ₹6,000 State), MP farmers receive a total of ₹12,000 annual direct income support.',
    benefitHi: 'पीएम-किसान के पात्र सभी कृषकों को मध्य प्रदेश सरकार द्वारा ₹6,000 प्रति वर्ष (₹2,000 की 3 किस्तों में) अतिरिक्त डीबीटी। केंद्र (₹6,000) + राज्य (₹6,000) = कुल ₹12,000 वार्षिक प्रत्यक्ष आय सहायता।',
    eligibilityEn: 'All farmers of Madhya Pradesh who are registered and verified beneficiaries under PM-KISAN.',
    eligibilityHi: 'मध्य प्रदेश के वे सभी किसान जो पीएम-किसान योजना के सत्यापित लाभार्थी हैं।',
    subsidyRate: '₹6,000 State DBT (Total ₹12,000)',
    documentsRequired: [
      { en: 'PM-KISAN Registration ID / Aadhaar Card', hi: 'पीएम-किसान पंजीकरण आईडी / आधार कार्ड' },
      { en: 'Aadhaar NPCI linked bank account', hi: 'आधार एनपीसीआई से जुड़ा बैंक खाता' },
      { en: 'Land Record (Khasra / B-1)', hi: 'खसरा / बी-1 भू-अभिलेख' }
    ],
    applicationMethodEn: 'Auto-enrolled through SAARA portal (saara.mp.gov.in) based on Patwari field verification.',
    applicationMethodHi: 'पटवारी सत्यापन उपरांत सारा (SAARA) पोर्टल saara.mp.gov.in द्वारा स्वचालित संयोजन।',
    portalUrl: 'https://saara.mp.gov.in',
    tollFreeContact: '181 (CM Helpline) / 0755-2555582',
    statusBadge: '₹6,000 State Cash DBT',
    featured: true,
    tags: ['madhya pradesh', 'dbt', 'income', 'pmkisan']
  },
  {
    id: 'bhavantar-mp',
    name: 'Bhavantar Bhugtan Yojana MP (भावांतर भुगतान योजना)',
    hindiName: 'भावांतर भुगतान योजना (समर्थन मूल्य अंतर भुगतान)',
    ministry: 'Farmer Welfare & Agriculture Development Dept, MP',
    isCentral: false,
    state: 'Madhya Pradesh',
    stateHi: 'मध्य प्रदेश',
    priority: 91,
    category: 'income_credit',
    categoryLabelEn: 'Price Deficiency Compensation',
    categoryLabelHi: 'भाव अंतर सुरक्षा',
    benefitEn: 'Price deficiency payment scheme directly depositing the price gap between notified MSP and actual mandi auction sale price into bank accounts for soybean, groundnut, sesame, moong, and urad.',
    benefitHi: 'सोयाबीन, मूंगफली, तिल, मूंग और उड़द हेतु न्यूनतम समर्थन मूल्य (MSP) और मंडी विक्रय मूल्य के अंतर (भावांतर) का सीधा भुगतान किसान के बैंक खाते में।',
    eligibilityEn: 'Farmers of MP registered on e-Uparjan portal selling notified oilseeds and pulses in APMC mandis.',
    eligibilityHi: 'मध्य प्रदेश के किसान जिन्होंने ई-उपार्जन पोर्टल पर पंजीकरण कराया है।',
    subsidyRate: '100% Price Gap Deficit Refund',
    documentsRequired: [
      { en: 'e-Uparjan Registration Receipt', hi: 'ई-उपार्जन पंजीकरण रसीद' },
      { en: 'Mandi Sale Invoice (Anugya Patra)', hi: 'मंडी विक्रय रसीद (अनुज्ञा पत्र)' },
      { en: 'Bank Account Passbook with Aadhaar link', hi: 'आधार लिंक्ड बैंक पासबुक' }
    ],
    applicationMethodEn: 'Register on mpeuparjan.nic.in during crop notification window and sell produce in registered mandis.',
    applicationMethodHi: 'अधिसूचना अवधि में mpeuparjan.nic.in पर पंजीकरण करें और पंजीकृत मंडियों में माल बेचें।',
    portalUrl: 'https://mpeuparjan.nic.in',
    tollFreeContact: '181 (CM Helpline)',
    statusBadge: 'Price Deficit Protection',
    featured: false,
    tags: ['madhya pradesh', 'mandi', 'msp', 'bhavantar']
  },

  // --- RAJASTHAN (राजस्थान) ---
  {
    id: 'rajasthan-mitra-urja',
    name: 'Mukhyamantri Kisan Mitra Urja Yojana (मुख्यमंत्री किसान मित्र ऊर्जा योजना)',
    hindiName: 'किसान मित्र ऊर्जा योजना (₹1,000/माह बिजली बिल सब्सिडी)',
    ministry: 'Energy Department, Govt of Rajasthan',
    isCentral: false,
    state: 'Rajasthan',
    stateHi: 'राजस्थान',
    priority: 96,
    category: 'solar_energy',
    categoryLabelEn: 'Direct Electricity Bill Grant',
    categoryLabelHi: 'बिजली बिल अनुदान (₹12,000/वर्ष)',
    benefitEn: 'Direct electricity bill subsidy of ₹1,000 per month (up to ₹12,000 per year) credited directly into agricultural metered electricity accounts of all general category farming families across Rajasthan.',
    benefitHi: 'कृषि बिजली उपभोक्ताओं को प्रतिमाह ₹1,000 (अधिकतम ₹12,000 प्रति वर्ष) की प्रत्यक्ष बिजली बिल सब्सिडी। छोटे किसानों का बिजली बिल लगभग शून्य।',
    eligibilityEn: 'All general agricultural metered power consumers in Rajasthan without outstanding arrears.',
    eligibilityHi: 'राजस्थान के सभी सामान्य श्रेणी कृषि मीटर उपभोक्ता किसान।',
    subsidyRate: '₹12,000 / Year Power Subsidy',
    documentsRequired: [
      { en: 'Agriculture Electricity Bill (K-Number)', hi: 'कृषि बिजली बिल (के-नंबर)' },
      { en: 'Jan Aadhaar Card', hi: 'जन आधार कार्ड' },
      { en: 'Bank Account linked to Jan Aadhaar', hi: 'जन आधार लिंक्ड बैंक खाता' }
    ],
    applicationMethodEn: 'Automatic credit on electricity bill upon linking Jan Aadhaar with power distribution discom.',
    applicationMethodHi: 'बिजली निगम में जन आधार लिंक कराने पर बिजली बिल में स्वतः छूट लागू।',
    portalUrl: 'https://energy.rajasthan.gov.in',
    tollFreeContact: '1800-180-6030',
    statusBadge: '₹12,000/Yr Power Grant',
    featured: true,
    tags: ['rajasthan', 'electricity', 'energy', 'power']
  },
  {
    id: 'rajasthan-tarbandi',
    name: 'Rajasthan Khet Tarbandi Yojana (खेत तारबंदी योजना - 50% अनुदान)',
    hindiName: 'खेत तारबंदी योजना (नीलगाय व आवारा पशु सुरक्षा)',
    ministry: 'Department of Agriculture, Govt of Rajasthan (RajKisan Sathi)',
    isCentral: false,
    state: 'Rajasthan',
    stateHi: 'राजस्थान',
    priority: 93,
    category: 'mechanization_infra',
    categoryLabelEn: 'Crop Protection Wire Fencing',
    categoryLabelHi: 'तारबंदी 50% अनुदान',
    benefitEn: 'Financial grant of 50% cost (up to ₹40,000 or 400 running meters of fencing) to install galvanized barbed wire / chain-link fencing around farm boundaries to protect crops from nilgai, wild boars, and stray cattle.',
    benefitHi: 'नीलगाय एवं आवारा पशुओं से फसल सुरक्षा हेतु 400 मीटर तक कंटीले तार की बाड़ लगाने पर 50% (अधिकतम ₹40,000) सरकारी अनुदान।',
    eligibilityEn: 'Individual farmers having at least 1.5 hectares cultivable land, or groups of farmers pooling contiguous lands.',
    eligibilityHi: 'न्यूनतम 1.5 हेक्टेयर कृषि भूमि वाले किसान अथवा किसानों का समूह।',
    subsidyRate: '50% Subsidy (Up to ₹40,000)',
    documentsRequired: [
      { en: 'Jan Aadhaar Card and Aadhaar Card', hi: 'जन आधार कार्ड एवं आधार कार्ड' },
      { en: 'Jamabandi Land Revenue Record (not older than 6 months)', hi: 'जमाबंदी नकल (6 माह से अधिक पुरानी न हो)' },
      { en: 'Bank Passbook and Field Map (Naksha Trace)', hi: 'बैंक पासबुक एवं खेत का नक्शा ट्रेस' }
    ],
    applicationMethodEn: 'Apply online on RajKisan Sathi Portal (rajkisan.rajasthan.gov.in) through SSO ID or nearest e-Mitra kiosk.',
    applicationMethodHi: 'राजकिसान साथी पोर्टल (rajkisan.rajasthan.gov.in) पर एसएसओ आईडी अथवा ई-मित्र से ऑनलाइन आवेदन करें।',
    portalUrl: 'https://rajkisan.rajasthan.gov.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: '50% Fencing Grant',
    featured: false,
    tags: ['rajasthan', 'fencing', 'protection', 'tarbandi']
  },

  // --- MAHARASHTRA (महाराष्ट्र) ---
  {
    id: 'namo-shetkari-maharashtra',
    name: 'Namo Shetkari Mahasanman Nidhi Yojana (नमो शेतकरी महासन्मान निधी)',
    hindiName: 'नमो शेतकरी महासन्मान निधी (₹6,000 राज्य DBT)',
    ministry: 'Department of Agriculture, Govt of Maharashtra',
    isCentral: false,
    state: 'Maharashtra',
    stateHi: 'महाराष्ट्र',
    priority: 97,
    category: 'income_credit',
    categoryLabelEn: 'State Companion DBT',
    categoryLabelHi: 'राज्य सम्मान निधि (कुल ₹12,000)',
    benefitEn: 'Financial assistance of ₹6,000 per year transferred directly in 3 installments into bank accounts of farmers eligible under PM-KISAN, making total annual DBT ₹12,000 (Central ₹6,000 + Maharashtra ₹6,000).',
    benefitHi: 'पीएम-किसान के सभी पात्र किसानों को महाराष्ट्र सरकार द्वारा ₹6,000 प्रति वर्ष अतिरिक्त अनुदान। केंद्र (₹6,000) + राज्य (₹6,000) = कुल ₹12,000 प्रति वर्ष।',
    eligibilityEn: 'All landholding farmers in Maharashtra successfully enrolled and receiving PM-KISAN benefits.',
    eligibilityHi: 'महाराष्ट्र के वे सभी किसान जो पीएम-किसान योजना के अंतर्गत पंजीकृत हैं।',
    subsidyRate: '₹6,000 State DBT (Total ₹12,000)',
    documentsRequired: [
      { en: 'PM-KISAN Farmer ID and Aadhaar Card', hi: 'पीएम-किसान आईडी एवं आधार कार्ड' },
      { en: 'Aadhaar NPCI Bank Account Linkage', hi: 'आधार एनपीसीआई बैंक सीडिंग' },
      { en: '7/12 Land Record and 8A extract', hi: '7/12 उतारा एवं 8अ नोंद' }
    ],
    applicationMethodEn: 'Auto-enrolled via MahaDBT portal based on verified PM-KISAN beneficiary database.',
    applicationMethodHi: 'महाडीबीटी (MahaDBT) पोर्टल पर पीएम-किसान डेटाबेस से स्वतः लाभ वितरण।',
    portalUrl: 'https://mahadbt.maharashtra.gov.in',
    tollFreeContact: '022-49150800',
    statusBadge: '₹6,000 State Cash DBT',
    featured: true,
    tags: ['maharashtra', 'dbt', 'shetkari', 'income']
  },
  {
    id: 'gopinath-munde-vima',
    name: 'Gopinath Munde Shetkari Apghat Vima Yojana (गोपीनाथ मुंडे शेतकरी अपघात विमा)',
    hindiName: 'गोपीनाथ मुंडे शेतकरी अपघात विमा (₹2 लाख मुफ्त कवर)',
    ministry: 'Department of Agriculture, Govt of Maharashtra',
    isCentral: false,
    state: 'Maharashtra',
    stateHi: 'महाराष्ट्र',
    priority: 92,
    category: 'insurance_risk',
    categoryLabelEn: '100% Free Accidental Insurance',
    categoryLabelHi: 'निःशुल्क दुर्घटना सुरक्षा',
    benefitEn: '100% state-funded accident and permanent disability life insurance coverage of up to ₹2,00,000 for all registered agricultural landholders and one family member aged 10-75 years, with zero premium paid by the farmer.',
    benefitHi: 'खेत में काम करते समय दुर्घटना मृत्यु या स्थायी अपंगता होने पर ₹2,00,000 तक की निःशुल्क बीमा सहायता। किसान को कोई प्रीमियम नहीं देना होता।',
    eligibilityEn: 'Registered 7/12 landholding farmers and one nominated family member in Maharashtra aged 10-75.',
    eligibilityHi: 'महाराष्ट्र के 7/12 भू-धारक किसान एवं परिवार का एक सदस्य (आयु 10 से 75 वर्ष)।',
    subsidyRate: '100% Free - Zero Premium',
    documentsRequired: [
      { en: '7/12 and 8A Land Extract', hi: '7/12 व 8अ उतारा' },
      { en: 'Police FIR / Panchnama in case of accident', hi: 'पुलिस पंचनामा / एफआईआर' },
      { en: 'Post-mortem report or Disability certificate', hi: 'पोस्टमार्टम रिपोर्ट या अपंगता प्रमाण पत्र' }
    ],
    applicationMethodEn: 'Submit claim papers within 30 days of accident to Taluka Krishi Adhikari (TKA) office.',
    applicationMethodHi: 'दुर्घटना के 30 दिनों के भीतर तालुका कृषि अधिकारी कार्यालय में दावा पत्र जमा करें।',
    portalUrl: 'https://krishi.maharashtra.gov.in',
    tollFreeContact: '1800-233-4000',
    statusBadge: '₹2 Lakh Free Cover',
    featured: false,
    tags: ['maharashtra', 'insurance', 'accident', 'social_security']
  },

  // --- GUJARAT (ગુજરાત / गुजरात) ---
  {
    id: 'saat-pagla-khedut-gujarat',
    name: 'Saat Pagla Khedut Kalyan Na (સાત પગલાં ખેડૂત કલ્યાણના - 7 Steps for Farmers)',
    hindiName: 'सात पगला खेड़ूत कल्याण योजना (गौ-पालन, तारबंदी व ड्रम किट)',
    ministry: 'Department of Agriculture, Farmers Welfare & Co-operation, Gujarat',
    isCentral: false,
    state: 'Gujarat',
    stateHi: 'गुजरात',
    priority: 95,
    category: 'organic_sustainable',
    categoryLabelEn: 'Holistic Farmer Welfare Package',
    categoryLabelHi: 'समग्र कृषक कल्याण पैकेज',
    benefitEn: 'Multi-benefit umbrella scheme offering: ₹900/month (₹10,800/year) maintenance subsidy for rearing indigenous desi cows, 50% subsidy for field wire fencing against wild animals, free plastic drum kits for organic liquid jeevamrut, and ₹30,000 subsidy for on-farm crop storage godowns.',
    benefitHi: 'देसी गाय पालन हेतु ₹900 प्रति माह (₹10,800/वर्ष), खेत तारबंदी पर 50% अनुदान, प्राकृतिक जीवामृत हेतु निःशुल्क प्लास्टिक ड्रम किट, एवं खेत पर माल भंडारण हेतु ₹30,000 की सब्सिडी।',
    eligibilityEn: 'Farmers residing in Gujarat practicing natural farming or owning land registered on iKhedut.',
    eligibilityHi: 'गुजरात के किसान जो प्राकृतिक खेती करते हैं अथवा आई-खेड़ूत पोर्टल पर पंजीकृत हैं।',
    subsidyRate: '₹10,800/Yr Cow Care + 50% Fencing',
    documentsRequired: [
      { en: 'iKhedut Registration Number', hi: 'आई-खेड़ूत पंजीकरण संख्या' },
      { en: '7/12, 8A Land Records', hi: '7/12 एवं 8अ भूमि रिकॉर्ड' },
      { en: 'Cow Tagging Certificate (for cow subsidy)', hi: 'गाय टैगिंग प्रमाण पत्र' }
    ],
    applicationMethodEn: 'Apply on iKhedut portal (ikhedut.gujarat.gov.in) when scheme windows are open.',
    applicationMethodHi: 'ikhedut.gujarat.gov.in पोर्टल पर ऑनलाइन आवेदन करें।',
    portalUrl: 'https://ikhedut.gujarat.gov.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: 'Holistic State DBT',
    featured: true,
    tags: ['gujarat', 'cow', 'organic', 'fencing', 'ikhedut']
  },

  // --- BIHAR (बिहार) ---
  {
    id: 'bihar-fasal-sahayata',
    name: 'Bihar Rajya Fasal Sahayata Yojana (बिहार राज्य फसल सहायता योजना)',
    hindiName: 'बिहार राज्य फसल सहायता योजना (100% नि:शुल्क फसल बीमा)',
    ministry: 'Cooperative Department, Govt of Bihar',
    isCentral: false,
    state: 'Bihar',
    stateHi: 'बिहार',
    priority: 96,
    category: 'insurance_risk',
    categoryLabelEn: 'Zero-Premium Crop Protection',
    categoryLabelHi: 'निःशुल्क फसल क्षति सुरक्षा',
    benefitEn: '100% Free disaster compensation without any insurance premium paid by farmers. If crop yield loss is up to 20%, farmers get ₹7,500 per hectare; if loss exceeds 20%, compensation is ₹10,000 per hectare (up to 2 hectares) deposited directly via DBT.',
    benefitHi: 'बिना किसी प्रीमियम भुगतान के 100% नि:शुल्क फसल सुरक्षा। 20% तक क्षति होने पर ₹7,500 प्रति हेक्टेयर तथा 20% से अधिक नुकसान पर ₹10,000 प्रति हेक्टेयर (अधिकतम 2 हेक्टेयर) सीधे बैंक खाते में।',
    eligibilityEn: 'All raiyat (landholding) and non-raiyat (tenant/sharecropper) farmers in Bihar cultivating notified crops.',
    eligibilityHi: 'बिहार के सभी रैयत एवं गैर-रैयत (बटाईदार) किसान।',
    subsidyRate: '₹7,500 to ₹10,000 / Hectare Free',
    documentsRequired: [
      { en: 'Land Possession Certificate (LPC) or Revenue Receipt', hi: 'भू-स्वामित्व प्रमाण पत्र (LPC) अथवा मालगुजारी रसीद' },
      { en: 'Self-declaration attested by Ward Member for non-raiyat', hi: 'गैर-रैयत हेतु वार्ड सदस्य द्वारा सत्यापित स्व-घोषणा पत्र' },
      { en: 'Aadhaar Card and Bank Passbook', hi: 'आधार कार्ड एवं बैंक पासबुक' }
    ],
    applicationMethodEn: 'Register on Bihar DBT Agriculture portal (dbtagriculture.bihar.gov.in) before harvest notification.',
    applicationMethodHi: 'dbtagriculture.bihar.gov.in पोर्टल पर फसल कटाई से पूर्व ऑनलाइन नि:शुल्क आवेदन करें।',
    portalUrl: 'https://dbtagriculture.bihar.gov.in',
    tollFreeContact: '1800-180-1551',
    statusBadge: '100% Free - Zero Premium',
    featured: true,
    tags: ['bihar', 'insurance', 'free', 'disaster', 'dbt']
  },

  // --- KARNATAKA (ಕರ್ನಾಟಕ / कर्नाटक) ---
  {
    id: 'raitha-siri-karnataka',
    name: 'Raitha Siri & Krishi Bhagya Scheme (ರೈತ ಸಿರಿ ಯೋಜನಾ)',
    hindiName: 'कर्नाटक रैत सिरी योजना (मोटा अनाज ₹10,000/हेक्टेयर)',
    ministry: 'Department of Agriculture, Govt of Karnataka',
    isCentral: false,
    state: 'Karnataka',
    stateHi: 'कर्नाटक',
    priority: 94,
    category: 'organic_sustainable',
    categoryLabelEn: 'Nutri-Cereal Incentive',
    categoryLabelHi: 'कदन्न / मोटा अनाज प्रोत्साहन',
    benefitEn: 'Financial incentive of ₹10,000 per hectare deposited directly via DBT into bank accounts of farmers cultivating nutri-cereals / minor millets (ragi, jowar, bajra, foxtail millet). Also provides up to 80-90% subsidy on farm pond polythene lining under Krishi Bhagya.',
    benefitHi: 'कदन्न / मोटे अनाज (रागी, ज्वार, बाजरा, फॉक्सटेल मिलेट) उगाने वाले किसानों को ₹10,000 प्रति हेक्टेयर नकद प्रोत्साहन सीधे डीबीटी द्वारा। कृषि भाग्य योजना के तहत खेत तलाई प्लास्टिक लाइनिंग पर 80-90% अनुदान।',
    eligibilityEn: 'Farmers in Karnataka growing notified millets on land verified through FRUITS (Farmer Registration and Unified Beneficiary Information System).',
    eligibilityHi: 'कर्नाटक के किसान जो फ्रूट्स (FRUITS) पोर्टल पर पंजीकृत हैं और मोटे अनाज की खेती करते हैं।',
    subsidyRate: '₹10,000 / Hectare Direct Incentive',
    documentsRequired: [
      { en: 'FRUITS Identification Number (FID)', hi: 'फ्रूट्स (FRUITS) आईडी संख्या' },
      { en: 'Pahani (RTC) Land Record', hi: 'पाहणी (RTC) भू-अभिलेख' },
      { en: 'Aadhaar Linked Bank Account', hi: 'आधार लिंक्ड बैंक खाता' }
    ],
    applicationMethodEn: 'Enroll at nearest Raitha Samparka Kendra (RSK) or apply via raitamitra.karnataka.gov.in.',
    applicationMethodHi: 'नजदीकी रैत संपर्क केंद्र (RSK) अथवा raitamitra.karnataka.gov.in पर आवेदन करें।',
    portalUrl: 'https://raitamitra.karnataka.gov.in',
    tollFreeContact: '1800-425-3553',
    statusBadge: '₹10,000/ha Millet Grant',
    featured: true,
    tags: ['karnataka', 'millets', 'fruits', 'dbt']
  }
];

export function listSchemes(filterCategory = null, filterState = null) {
  let list = SCHEMES_DATA;

  // State filtering logic
  if (filterState && filterState !== 'all') {
    const sQuery = filterState.toLowerCase().trim();
    if (sQuery === 'central') {
      list = list.filter(s => s.isCentral);
    } else {
      // Include state schemes matching this state AND all central schemes
      list = list.filter(s => s.isCentral || (s.state && s.state.toLowerCase() === sQuery));
      
      // Sort state schemes of matched state to the top, followed by central schemes by priority
      list = [...list].sort((a, b) => {
        const aIsState = !a.isCentral && a.state.toLowerCase() === sQuery;
        const bIsState = !b.isCentral && b.state.toLowerCase() === sQuery;
        if (aIsState && !bIsState) return -1;
        if (!aIsState && bIsState) return 1;
        return (b.priority || 50) - (a.priority || 50);
      });
    }
  } else {
    // Default sorting: high priority schemes first
    list = [...list].sort((a, b) => (b.priority || 50) - (a.priority || 50));
  }

  // Category filtering
  if (filterCategory && filterCategory !== 'all') {
    const catQuery = filterCategory.toLowerCase();
    list = list.filter(s => s.category.toLowerCase() === catQuery || (s.tags && s.tags.includes(catQuery)));
  }

  return list;
}

export function getSchemeById(id) {
  return SCHEMES_DATA.find(s => s.id === id) || null;
}

